### ISSUE TITLE
Allow AutoTest

### ISSUE THREAD

**Issue by roman-wedemeier** [jasmine/IdeaJasmine#16]
Please can you provide possibility to set the AutoTest delay? I looked into the code to provide you a pull request, but unfortunately i do not understand very much of plugin coding for Jetbrain IDEs. So my best bet is to please you to make that possible.

Besides thank you for the really helpful plugin and sorry for my poor english :-)

Kind regards

**Comment by slackersoft** [comment]
The Jasmine IntelliJ plugin doesn't know anything about AutoTest or how it might be configured within IntelliJ itself. It looks like this functionality is just part of the baseline IntelliJ (https://www.jetbrains.com/help/idea/performing-tests.html#run-tests-automatically) so it probably makes sense to look through the IntelliJ options and see if you can find the appropriate setting.
