### ISSUE TITLE
Simply doesn't work :(  [First run!]

### ISSUE THREAD

**Issue by iexcept** [jasmine/IdeaJasmine#3]
"C:\Program Files\nodejs\node.exe" C:\progs\idea\bin\bin\jasmine.js --reporter=C:\Users\user\.IntelliJIdea2018.1\config\plugins\IdeaJasmine\lib\intellij_reporter.js "C:/project/src/app/something.spec.ts"

module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\progs\idea\bin\bin\jasmine.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by slackersoft** [comment]
It looks like you haven't selected a Jasmine package in the run configuration. I haven't had time to really get in a fix the error messages for this yet, but please edit [your configuration](https://github.com/jasmine/IdeaJasmine#configure) to specify where the Jasmine package is located and see if this fixes your issue.

Hope this helps. Thanks for using Jasmine!
