### ISSUE TITLE
Node options lost when IntelliJ restarted

### ISSUE THREAD

**Issue by matthelliwell2** [jasmine/IdeaJasmine#9]
This is in IntelliJ Ultimate 2018.3.

I create a new Jasmine run configuration to run my Jasmine tests. As I am running Typescript, I set the following options in "Node Options":

"-r ts-node/register/transpile-only -r tsconfig-paths/register"

The tests run fine. However when I restart IntelliJ the the node options have gone and I need to re-enter them. Similarly if I set the node options in run/edit configurations->templates->jasmine, they are also lost when I restart IntelliJ.

I don't see this behavious in other plugins so I'm assuming that the issue is in the plugin rather than my machine or IntelliJ.

**Comment by slackersoft** [comment]
There was a breaking change to one of the interfaces that the plugin uses in the more recent versions of IntelliJ. We released version 1.4 of IdeaJasmine earlier this week, please update and let me know if you're still seeing this issue.

**Comment by matthelliwell2** [comment]
Works fine for me now thanks.
